#!/bin/bash
B="https://www.shuducw.com"
echo "===== 1. 新页 /services/delivery ====="
echo "  状态: $(curl -s -o /dev/null -w '%{http_code}' $B/services/delivery)"
echo "  7 节点: $(curl -s $B/services/delivery | grep -oE '签约与需求确认|建账与初始资料交接|每月账务处理|纳税申报|报表与凭证交付|年度事项办理|归档与年度复盘' | sort -u | wc -l)/7"
echo "  交付物标签: $(curl -s $B/services/delivery | grep -c '交付物：')"
echo "  责任边界(双向): $(curl -s $B/services/delivery | grep -cE '我们的责任|企业需配合的事项')"
echo "  Schema: $(curl -s $B/services/delivery | grep -c 'hasOfferCatalog')"
echo ""
echo "===== 2. 表单新增'方便联系时段' ====="
echo "  联系页: $(curl -s $B/contact | grep -c '方便联系时段')"
echo "  高新区县页: $(curl -s $B/services/district/gaoxin | grep -c '方便联系时段')"
echo ""
echo "===== 3. SEO 同步 ====="
echo "  sitemap 含 delivery: $(curl -s $B/sitemap.xml | grep -c 'delivery')  总URL: $(curl -s $B/sitemap.xml | grep -c '<loc>')"
echo "  llms.txt 含 delivery: $(curl -s $B/llms.txt | grep -c 'delivery')"
echo "  /services 页入口链接: $(curl -s $B/services | grep -c '查看完整服务流程与交付标准')"
echo "  页脚入口: $(curl -s $B/ | grep -c '服务交付标准')"
echo ""
echo "===== 4. 标题仍应为 1 次品牌 ====="
t=$(curl -s "$B/services/delivery" | grep -oE '<title>[^<]*</title>' | head -1 | sed 's/<[^>]*>//g')
echo "  [$(echo "$t" | grep -o '西安数度财务咨询' | wc -l)次] $t"
